alias gc='git checkout'
alias gs='git status'
alias gps='git push'
alias gpsf='git push --force'
alias gpl='git pull'
alias gcm='git checkout master || git checkout main'
alias gco='git commit'
alias grs='git reset --soft HEAD\^'
alias -g yamlb="-o yaml | bat -l yaml"
